apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: aggressive-finch-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aggressive-finch-nodejs 
  name: aggressive-finch-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: aggressive-finch-nodejs 
